"""empty message

Revision ID: 0573fa0e26d1
Revises: ea43e9a43113
Create Date: 2021-01-02 22:56:00.378667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0573fa0e26d1'
down_revision = 'ea43e9a43113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'timeline', ['eventkey'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline', type_='unique')
    # ### end Alembic commands ###
