"""timeline table

Revision ID: 473318c3e6c3
Revises: 
Create Date: 2021-01-03 09:19:57.904246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473318c3e6c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.Column('eventkey', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventkey')
    )
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_eventname'), ['eventname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_eventname'))

    op.drop_table('timeline')
    # ### end Alembic commands ###
