"""timeline table

Revision ID: 9194ccf395bb
Revises: 
Create Date: 2021-01-03 06:41:43.426428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9194ccf395bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_eventname'), 'timeline', ['eventname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_eventname'), table_name='timeline')
    op.drop_table('timeline')
    # ### end Alembic commands ###
