"""timeline table

Revision ID: c86261f54e90
Revises: 0863f821c208
Create Date: 2021-01-02 22:21:23.515913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86261f54e90'
down_revision = '0863f821c208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_eventkey', table_name='timeline')
    op.create_unique_constraint(None, 'timeline', ['eventkey'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline', type_='unique')
    op.create_index('ix_timeline_eventkey', 'timeline', ['eventkey'], unique=1)
    # ### end Alembic commands ###
