"""table update

Revision ID: ef6d9eab5b35
Revises: 
Create Date: 2021-01-05 04:22:18.092236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d9eab5b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('eventkey', sa.String(length=6), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('eventkey')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_eventkey'), ['eventkey'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_eventname'), ['eventname'], unique=False)

    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('eventkey', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['eventkey'], ['event.eventkey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_id'), ['id'], unique=False)

    op.create_table('timeblock',
    sa.Column('blockid', sa.Integer(), nullable=False),
    sa.Column('blockstart', sa.DateTime(), nullable=True),
    sa.Column('blockend', sa.DateTime(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('timelineid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timelineid'], ['timeline.id'], ),
    sa.PrimaryKeyConstraint('blockid')
    )
    with op.batch_alter_table('timeblock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeblock_blockid'), ['blockid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeblock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeblock_blockid'))

    op.drop_table('timeblock')
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_id'))

    op.drop_table('timeline')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_eventname'))
        batch_op.drop_index(batch_op.f('ix_event_eventkey'))

    op.drop_table('event')
    # ### end Alembic commands ###
